LC-303 Add WalletConnect fallback
LedgerHQ/connect-kit pull request #5
Opened 2022-10-24 16:15 UTC by hlopes-ledger

Add WalletConnect fallback

- UI: update texts, improved spacings, replaced Ledger Connect with Ledger
  logo
- src/lib
    - renamed files and added logging.ts
    - logger.ts, used to easily enable or disable debug messages for the
      entire project
    - support.ts, `checkSupport` sets the provider type and chain id from
      the arguments, determines provider implementation and sets it
    - provider.ts, we now only expose a `getProvider` function
      with no arguments that returns the correct provider based on the
      provider type and implementation that were set on `checkSupport`
- src/providers
    - renamed files and added WalletConnect
- src/providers/WalletConnect.ts
    - `initWalletConnect` is called from `checkSupport` if Connect is not
      supported on the user's platform, reuses the provider or creates a new
      instance, registers the "connect" event that will hide the Connect Kit
      modal when connected
    - the connect event was only firing once if assigned only when creating
      a new instance of the connector on `initWalletConnect`, we now set
      a flag on `hasAssignedProviderEvents` and assign them once when
      reusing the provider after it disconnects
    - `getWalletConnectUri` is called from the `ConnectWithLedgerLiveModal`
      component to get the WalletConnect URI
    - `getWalletConnectProvider` waits for the user to connect using LL
      and resolves with the enabled provider
- src/components/ConnectWithLedgerLiveModal
    - new `ConnectWithLedgerLiveModal` component, shown instead of the
      PlatformNotSupportedModal for Ethereum
    - has a withQrCode prop, we show the QR code only when on desktop
    - `useEffect` with no dependencies to call `getWalletConnectUri`
      and create LL deepling and QR code from WalletConnect's URI
- src/components/ExtensionUnavailableModal
    - new onboarding URL
    - button now labeled "Install now" instead of "Join the Beta"
- src/components/PlatformNotSupportedModal
    - removed mention to USB fallback on other browsers
- src/components/Modal
    - added Stack styled component to ease laying out QR code and side
      by side buttons

2022-10-26 09:33 UTC, chrisd-ledger requested changes

2022-10-26 09:33 UTC, chrisd-ledger commented on packages/connect-kit-loader/src/index.ts
> +export type ProviderResult = EthereumProvider | SolanaProvider;
you probably need to delete one of those

2022-10-26 09:33 UTC, chrisd-ledger commented on packages/connect-kit-loader/src/index.ts
>  function loadScript(src: string, globalName: string): Promise<any> {
this probably always returns void, can specify the type

2022-10-26 09:33 UTC, chrisd-ledger commented on packages/connect-kit/src/components/ConnectWithLedgerLiveModal/ConnectWithLedgerLiveModal.tsx
> +  })
i am pretty sure this use effect needs the dependecy array so it only gets initialized at runtime;
so
```
useEffect(() => {
  const uri = getWalletConnectUri();

 if(uri) {
  setWalletConnectUri(uri);
 }
}, [])
```

2022-10-26 09:33 UTC, chrisd-ledger commented on packages/connect-kit/src/components/ConnectWithLedgerLiveModal/ConnectWithLedgerLiveModal.tsx
> +  })
I didn't include the deeplink url, because why are we setting it in the state? looks like a normal variable to me not something we have to fetch at runtime

2022-10-26 09:33 UTC, chrisd-ledger commented on packages/connect-kit/src/components/ExtensionUnavailableModal/ExtensionUnavailableModal.styles.tsx
> +  margin: 12px 0 0q 0;
mistake, it says `0q`

2022-10-26 09:33 UTC, chrisd-ledger commented on packages/connect-kit/src/lib/logger.ts
> +export type Logger = (message: string, ...others: any[]) => void;
i feel like `unknown[]` would suit us better than `any[]`

2022-10-26 09:33 UTC, chrisd-ledger commented on packages/connect-kit/src/lib/logger.ts
> +const disabled = false;
why are we using a variable as a boolean here?

2022-10-26 09:33 UTC, chrisd-ledger commented on packages/connect-kit/src/lib/logger.ts
> +const disabled = false;
this will never change it will always be false

2022-10-26 09:33 UTC, chrisd-ledger commented on packages/connect-kit/src/lib/logger.ts
> +    if (disabled) return () => null;
this will never be the case

2022-10-26 09:33 UTC, chrisd-ledger commented on packages/connect-kit/src/lib/modal.tsx
> +export function showModal(modalType: ModalType, props?: {} ) {
what is the type of props? it seems like an empty object to me, not sure that works.
probably you are better off with an unknown

2022-10-26 09:33 UTC, chrisd-ledger commented on packages/connect-kit/src/lib/support.ts
> +    // swallow any error
maybe logError here?

2022-10-26 11:16 UTC, mitchellv-ledger requested changes
Some small things to address

2022-10-26 11:16 UTC, mitchellv-ledger commented on packages/connect-kit/src/lib/support.ts
> +    const ethereumProvider = getSolanaProvider();
you've called this `ethereumProvider` when it is solana

2022-10-26 11:16 UTC, mitchellv-ledger commented on packages/connect-kit/src/providers/WalletConnect.ts
> +}
```suggestion
export async function getWalletConnectProvider(): Promise<ProviderResult> {
    log('getWalletConnectProvider');

    try {
      await walletConnectProvider.enable();
      return walletConnectProvider;
    } catch (err) {
      logError('error', err);

      let error: Error;

      if (err instanceof Error) {
        error = err
      } else {
        error = new Error(String(err))
      }

      throw new Error(error);
    }
}
```
As it is right now it won't catch errors from `walletConnectProvider.enable()` as the try catch does nothing and it would need to move that part to here `walletConnectProvider.enable().then(...).catch(error => {...})` if you don't change to async await

2022-10-26 11:26 UTC, hlopes-ledger commented on packages/connect-kit-loader/README.md
> +  yet;
I was using that style of bullet point punctuation in which you put a semicolon at ehe end of all of them except the last one, but it seems that is when it is all part of a single phrase. Will change that to a period.

https://www.instructionalsolutions.com/blog/bulleted-list-punctuation

2022-10-26 11:32 UTC, hlopes-ledger commented on packages/connect-kit-loader/src/index.ts
> +  const CONNECT_KIT_CDN_URL = "https://idyllic-kelpie-25742f.netlify.app/umd/index.js";
I didn't want to replace the deployment of the original version of Connect Kit, so I deployed the version with the WalletConnect fallback to a new site. The final version of Connect Kit will be loaded from unpkg.org, so this is just a test URL.

2022-10-26 11:37 UTC, hlopes-ledger commented on packages/connect-kit/src/components/ConnectWithLedgerLiveModal/ConnectWithLedgerLiveModal.tsx
> +  })
Yep, the deeplink needs to be updated with the value of the uri.

If I set the dependency array to [] it only runs once and is not updated with the final uri after WalletConnect initialises.

2022-10-26 11:51 UTC, hlopes-ledger commented on packages/connect-kit/src/components/ConnectWithLedgerLiveModal/ConnectWithLedgerLiveModal.tsx
> +  })
actually it seems to consistently get the uri now by running just once, but had problems with that before where the first uri it got was not valid

2022-10-26 12:43 UTC, hlopes-ledger commented on packages/connect-kit/src/lib/logger.ts
> +const disabled = false;
My initial thought was to just have a way to enable and log messages by changing it manually, just to diagnose some problem if needed.
I have now exposed an `enableDebugLogs` function to enable and disable logging from outside at runtime. I'll update the PR today.

2022-10-26 12:45 UTC, hlopes-ledger commented on packages/connect-kit/src/lib/logger.ts
> +    if (disabled) return () => null;
yes, it was meant to be updated manually at build time but I'll update the PR

2022-10-26 12:54 UTC, hlopes-ledger commented on packages/connect-kit/src/lib/modal.tsx
> +export function showModal(modalType: ModalType, props?: {} ) {
it's was just a way to pass a props object to any of the components without having to explicitly import them, not much better than any

unknown is not assignable but since only ConnectWithLedgerLiveModalProps takes props I'll update it to match that

2022-10-26 12:56 UTC, hlopes-ledger commented on packages/connect-kit/src/lib/provider.ts
> +  return chainId === ConnectSupportedChains.EthereumMainnet;
yes, Connect will only work for Ethereum Mainnet for now, other chainIds will fallback to WalletConnect

2022-10-26 12:58 UTC, hlopes-ledger commented on packages/connect-kit/src/lib/provider.ts
> +  setProviderImplementation: SupportedProviderImplementations
must have been renamed by mistake, thanks

2022-10-26 13:00 UTC, hlopes-ledger commented on packages/connect-kit/src/lib/support.ts
> +    const ethereumProvider = getSolanaProvider();
woops, copy and paste

2022-10-26 13:04 UTC, chrisd-ledger commented on packages/connect-kit/src/components/ConnectWithLedgerLiveModal/ConnectWithLedgerLiveModal.tsx
> +  })
Oh, sorry, my bad. Then wouldn't the solution to always have an URI would be to move the uri outside and add it to the dep array? @hlopes-ledger @mitchellv-ledger

2022-10-26 13:10 UTC, hlopes-ledger commented on packages/connect-kit/src/providers/WalletConnect.ts
> +}
nice catch

2022-10-26 14:05 UTC, hlopes-ledger commented on packages/connect-kit-loader/src/index.ts
>  function loadScript(src: string, globalName: string): Promise<any> {
The initial thought was to have `loadScript` as a generic script loader and `loadConnectKit` as a more specific version that returns a `Promise<LedgerConnectKit>`. The return types of loadScript and loadConnectKit must be compatible so loadScript can only return `Promise<any>` or `Promise<LedgerConnectKit>`.

Since we'll not load other scripts I've merged both functions and return the specific type now.

2022-10-26 14:09 UTC, hlopes-ledger commented on packages/connect-kit/src/components/ConnectWithLedgerLiveModal/ConnectWithLedgerLiveModal.tsx
> +  })
Did some more tests and found the problem. It always gets the correct URI the first time, but if you disconnect and try to connect again it will use the same URI, which is now invalid. So after a disconnect it will need to get a new value from the WalletConnect module. I'll do some more tests.

2022-10-27 10:35 UTC, hlopes-ledger commented on packages/connect-kit/src/lib/support.ts
> +    // swallow any error
we don't need it
we're just checking to see if the extension is there, if it is not well fallback to WalletConnect, no need to show that on the console

2022-10-27 10:35 UTC, hlopes-ledger commented on packages/connect-kit-loader/src/index.ts
> +export type ProviderResult = EthereumProvider | SolanaProvider;
fixed

2022-10-27 10:36 UTC, hlopes-ledger commented on packages/connect-kit/src/components/ConnectWithLedgerLiveModal/ConnectWithLedgerLiveModal.tsx
> +  })
I've changed the process, explained in the last commit message

2022-10-27 10:38 UTC, hlopes-ledger commented on packages/connect-kit/src/lib/logger.ts
> +export type Logger = (message: string, ...others: any[]) => void;
fixed

2022-10-27 15:28 UTC, mitchellv-ledger approved these changes
Looks good!

2022-10-27 16:49 UTC, chrisd-ledger approved these changes
Approved

2022-10-27 17:02 UTC, merged

2023-12-15 09:42 UTC, ttloves2 reviewed
👋